name: Unit tests

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true

    strategy:
      matrix: 
        scheme: [
          WordFeatureTests, 
          PossibleWordsTests, 
          FinanceComparisonTests
        ]
      
    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Test ${{ matrix.scheme }} feature
        run: xcodebuild build-for-testing test-without-building -scheme ${{ matrix.scheme }}  -project WordyMe.xcodeproj -destination "platform=iOS Simulator,name=iPhone 14 Pro Max" -quiet

      - name: Save cache
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
