name: Unit tests

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    concurrency: ci-${{ github.ref }}

    runs-on: self-hosted

    strategy:
      matrix: 
        scheme: [
          WordFeatureTests, 
          PossibleWordsTests, 
          FinanceComparisonTests
        ]
      
    steps:
      - uses: actions/checkout@v3

      - name: Test ${{ matrix.scheme }} feature
        run: xcodebuild build-for-testing -scheme ${{ matrix.scheme }} -project WordyMe.xcodeproj -destination "platform=iOS Simulator,name=iPhone 14 Pro Max" -quiet

  concurrent_builds:
    concurrency: ci-${{ github.ref }}

    needs: [build]

    strategy:
      matrix: 
        scheme: [
          WordFeatureTests, 
          PossibleWordsTests, 
          FinanceComparisonTests
        ]

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Test ${{ matrix.scheme }} feature
        run: xcodebuild test-without-building -scheme ${{ matrix.scheme }} -project WordyMe.xcodeproj -destination "platform=iOS Simulator,name=iPhone 14 Pro Max" -quiet

      - name: Slack Webhook for GitHub Actions
        uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
